[package]
name = "rust_speech"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Used for easy way to define onw error type
thiserror = "1.0.40"
